platform :ios, :deployment_target => "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target 'TBAlertController', :exclusive => true do
  pod "TBAlertController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TBAlertController", :path => "../"

  pod 'FBSnapshotTestCase'
end
